---

- hosts: all
  become: no
  remote_user: centos
  tasks:
    - setup:
      failed_when: false
      ignore_unreachable: yes

    - meta: clear_host_errors

- hosts: all
  become: no
  remote_user: rocky
  tasks:
    - setup:
      failed_when: false
      ignore_unreachable: yes

    - meta: clear_host_errors

- hosts: all
  become: no
  remote_user: debian
  tasks:
    - setup:
      failed_when: false
      ignore_unreachable: yes

    - meta: clear_host_errors

- hosts: all
  become: no
  remote_user: ubuntu
  tasks:
    - setup:
      failed_when: false
      ignore_unreachable: yes

    - meta: clear_host_errors

- hosts: all
  become: no
  remote_user: root
  tasks:
    - setup:
      failed_when: false
      ignore_unreachable: yes

    - meta: clear_host_errors

- hosts: all
  become: no
  tasks:
    - group_by:
        key: "{{ ansible_distribution }}"
      changed_when: false
      failed_when: false
      ignore_unreachable: yes

    - debug:
        var: groups
      failed_when: false
      ignore_unreachable: yes
      run_once: true
