---

- name: Setup CentOS
  setup:
  become: no
  remote_user: centos
  failed_when: false
  ignore_unreachable: yes

- name: Clear Centos
  meta: clear_host_errors

- name: Setup Rocky
  setup:
  become: no
  remote_user: rocky
  failed_when: false
  ignore_unreachable: yes

- name: Clear Rocky
  meta: clear_host_errors

- name: Setup Debian
  setup:
  become: no
  remote_user: debian
  failed_when: false
  ignore_unreachable: yes

- name: Clear Debian
  meta: clear_host_errors

- name: Setup Ubuntu
  setup:
  become: no
  remote_user: ubuntu
  failed_when: false
  ignore_unreachable: yes

- name: Clear Ubuntu
  meta: clear_host_errors

- name: Setup root
  setup:
  become: no
  remote_user: root
  failed_when: false
  ignore_unreachable: yes

- name: Clear root
  meta: clear_host_errors

- name: Group hosts by distribution
  group_by:
    key: "{{ ansible_distribution }}"
  changed_when: false
  failed_when: false
  ignore_unreachable: yes

- name: Put out all groups
  debug:
    var: groups
  failed_when: false
  ignore_unreachable: yes
  run_once: true
